name: Check PR source branch

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/check-pr-source-branch
